
package GUI;

import Domain.SocialWebCore;
import java.io.IOException;

import org.jdom.JDOMException;

public class JFWindow extends javax.swing.JFrame {

    protected static SocialWebCore socialWebCore;

    public JFWindow() throws JDOMException, IOException, CloneNotSupportedException {
        initComponents();
        JFWindow.socialWebCore = new SocialWebCore();
        this.setSize(800,600);
        this.add(new JPLogin(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}